"""your message

Revision ID: 98611df9ed07
Revises: e83a13a3de58
Create Date: 2024-01-31 23:13:45.338008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98611df9ed07'
down_revision = 'e83a13a3de58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
