"""migrations update

Revision ID: e462fc00ef8e
Revises: cdfc18592534
Create Date: 2024-01-31 23:03:03.551152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e462fc00ef8e'
down_revision = 'cdfc18592534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
